/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: agustin.trezza (https://sketchfab.com/agustin.trezza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/javascript-1-e6a5af39d2b3495fb4fb1f8f94d3efda
Title: Javascript (1)
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const Jslogo= (props) => {
  const { nodes, materials } = useGLTF('Jslogo/javascriptlogo.glb')
  return (
    <Float floatIntensity={5}>
        <group position={[0,0,0]} scale={0.01} {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.mat_3220964}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      </group>
    </Float>
  )
}

useGLTF.preload('Jslogo/javascriptlogo.glb')

export default Jslogo